- name: Create apiserver-deployer group
  group:
    name: apiserver-deployer
    gid: 954

- name: Create apiserver-deployer user
  user:
    name: apiserver-deployer
    group: apiserver-deployer
    uid: 954

- name: Create apiserver deployment directory
  file:
    path: /opt/apiserver/versions
    state: directory
    recurse: true
    owner: apiserver-deployer
    group: apiserver-deployer
    mode: 0755

- name: Install apiserver-deployer
  copy:
    src: apiserver-deployer.sh
    dest: /usr/local/bin/apiserver-deployer
    owner: root
    group: root
    mode: 0755
  notify: Restart apiserver-deployer

- name: Install apiserver-deployer systemd unit
  copy:
    src: apiserver-deployer.service
    dest: /etc/systemd/system/apiserver-deployer.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart apiserver-deployer
